improvements to the bin/... scripts

diff --git a/bin/mo-addrepo b/bin/mo-addrepo
--- a/bin/mo-addrepo
+++ b/bin/mo-addrepo
@@ -3,11 +3,37 @@
 # Usage:
 #    bin/mo-addrepo REPO NAME
 
+#export PS4='${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
+#set -o xtrace
+set -o errexit
+set -o pipefail
+
+
+function fatal
+{
+    echo "$(basename $0): fatal error: $*"
+    echo ""
+    echo "Usage:"
+    echo "  bin/mo-addrepo REPO NAME"
+    exit 1
+}
+
+
+
 REPO=$1
 NAME=$2
+if [[ -z "$REPO" ]]; then
+    fatal "no 'REPO' argument given"
+fi
+if [[ -z "$NAME" ]]; then
+    fatal "no 'NAME' argument given"
+fi
+
+
 
 if [[ -z "$MOLYBDENUM_URL" ]]; then
-    MOLYBDENUM_URL="http://localhost:3333"
+    echo "error: could not determine Molybdenum URL, set 'MOLYBDENUM_URL' envvar"
+    exit 1
 fi
 CURL_OPTS=
 if [[ ! -z "$MOLYBDENUM_CREDENTIALS" ]]; then
@@ -16,6 +42,7 @@ fi
 if [[ ${MOLYBDENUM_URL:0:6} == "https:" ]]; then
     CURL_OPTS+=" -k"
 fi
+
 
 
 echo "{\"repository\": {\"url\": \"$REPO\", \"name\": \"$NAME\"}}" \
diff --git a/bin/mo-listrepos b/bin/mo-listrepos
--- a/bin/mo-listrepos
+++ b/bin/mo-listrepos
@@ -3,14 +3,16 @@
 # Usage:
 #    bin/mo-listrepos
 
-#export PS4='${BASH_SOURCE}:${LINENO}: '
+#export PS4='${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
 #set -o xtrace
+set -o errexit
+set -o pipefail
 
-REPO=$1
-NAME=$2
+
 
 if [[ -z "$MOLYBDENUM_URL" ]]; then
-    MOLYBDENUM_URL="http://localhost:3333"
+    echo "error: could not determine Molybdenum URL, set 'MOLYBDENUM_URL' envvar"
+    exit 1
 fi
 CURL_OPTS=
 if [[ ! -z "$MOLYBDENUM_CREDENTIALS" ]]; then
@@ -19,6 +21,8 @@ fi
 if [[ ${MOLYBDENUM_URL:0:6} == "https:" ]]; then
     CURL_OPTS+=" -k"
 fi
+
+
 
 curl ${CURL_OPTS} -H "Content-Type: application/json" \
     ${MOLYBDENUM_URL}/api/repos
